### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by zsmm** [wustl-cig/DOLCE#4]
Hello! I downloaded your GitHub project and find it really intriguing. However, I couldn't locate the training code in the repository. Would you mind sharing the training code or providing guidance on effectively training the model?  Thank you!

**Comment by JiamingLiu-Jeremy** [comment]
Hi, the training can be easily done by following this link:https://github.com/openai/improved-diffusion when have the paired dataset available. The dataset download link can be found at bottom of this repo.
