### ISSUE TITLE
Request the 3D render tool

### ISSUE THREAD

**Issue by Lxy98Code** [wustl-cig/DOLCE#6]
Hi,

Thanks for releasing the codes and pretrained models. The work is very interesting! I was wondering if you'd like to share the tool you used to render the 3D results shown in Fig. 1, subfig 1 and 2? Thanks in advance!
Great paper btw!

Cheers,

**Comment by JiamingLiu-Jeremy** [comment]
Thank you for showing interest in our work ! We apply Napari for interactively visualizing. Will add the files shortly.
