### ISSUE TITLE
Error when loading the provided checkpoint: Missing key(s) in state_dict

### ISSUE THREAD

**Issue by ForMyCat** [wustl-cig/DOLCE#8]
Any idea on what's going on here? I am using the checkpoints you provided. 

Traceback (most recent call last):
  File "/usr/project/DOLCE/limited_ct_sample.py", line 187, in <module>
    main()
  File "/usr/project/DOLCE/limited_ct_sample.py", line 62, in main
    model.load_state_dict(
  File "/root/miniconda3/envs/dolce/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
**RuntimeError: Error(s) in loading state_dict for ConditionalModel:**
        **Missing key(s) in state_dict:** "input_blocks.3.0.op.weight", "input_blocks.3.0.op.bias", "input_blocks.6.0.op.weight", "input_blocks.6.0.op.bias", "input_blocks.9.0.op.weight", "input_blocks.9.0.op.bias", "input_blocks.12.0.op.weight", "input_blocks.12.0.op.bias", "input_blocks.15.0.op.weight", "input_blocks.15.0.op.bias", "input_blocks.18.0.op.weight", "input_blocks.18.0.op.bias", "output_blocks.2.4.conv.weight", "output_blocks.2.4.conv.bias", "output_blocks.5.4.conv.weight", "output_blocks.5.4.conv.bias", "output_blocks.8.3.conv.weight", "output_blocks.8.3.conv.bias", "output_blocks.11.3.conv.weight", "output_blocks.11.3.conv.bias", "output_blocks.14.1.conv.weight", "output_blocks.14.1.conv.bias", "output_blocks.17.1.conv.weight", "output_blocks.17.1.conv.bias". 
        **Unexpected key(s) in state_dict:** "input_blocks.3.0.in_layers.0.weight", "input_blocks.3.0.in_layers.0.bias", "input_blocks.3.0.in_layers.2.weight", "input_blocks.3.0.in_layers.2.bias", "input_blocks.3.0.emb_layers.1.weight", "input_blocks.3.0.emb_layers.1.bias", "input_blocks.3.0.out_layers.0.weight", "input_blocks.3.0.out_layers.0.bias", "input_blocks.3.0.out_layers.3.weight", "input_blocks.3.0.out_layers.3.bias", "input_blocks.6.0.in_layers.0.weight", "input_blocks.6.0.in_layers.0.bias", "input_blocks.6.0.in_layers.2.weight", "input_blocks.6.0.in_layers.2.bias", "input_blocks.6.0.emb_layers.1.weight", "input_blocks.6.0.emb_layers.1.bias", "input_blocks.6.0.out_layers.0.weight", "input_blocks.6.0.out_layers.0.bias", "input_blocks.6.0.out_layers.3.weight", "input_blocks.6.0.out_layers.3.bias", "input_blocks.9.0.in_layers.0.weight", "input_blocks.9.0.in_layers.0.bias", "input_blocks.9.0.in_layers.2.weight", "input_blocks.9.0.in_layers.2.bias", "input_blocks.9.0.emb_layers.1.weight", "input_blocks.9.0.emb_layers.1.bias", "input_blocks.9.0.out_layers.0.weight", "input_blocks.9.0.out_layers.0.bias", "input_blocks.9.0.out_layers.3.weight", "input_blocks.9.0.out_layers.3.bias", "input_blocks.12.0.in_layers.0.weight", "input_blocks.12.0.in_layers.0.bias", "input_blocks.12.0.in_layers.2.weight", "input_blocks.12.0.in_layers.2.bias", "input_blocks.12.0.emb_layers.1.weight", "input_blocks.12.0.emb_layers.1.bias", "input_blocks.12.0.out_layers.0.weight", "input_blocks.12.0.out_layers.0.bias", "input_blocks.12.0.out_layers.3.weight", "input_blocks.12.0.out_layers.3.bias", "input_blocks.13.3.norm.weight", "input_blocks.13.3.norm.bias", "input_blocks.13.3.qkv.weight", "input_blocks.13.3.qkv.bias", "input_blocks.13.3.proj_out.weight", "input_blocks.13.3.proj_out.bias", "input_blocks.14.3.norm.weight", "input_blocks.14.3.norm.bias", "input_blocks.14.3.qkv.weight", "input_blocks.14.3.qkv.bias", "input_blocks.14.3.proj_out.weight", "input_blocks.14.3.proj_out.bias", "input_blocks.15.0.in_layers.0.weight", "input_blocks.15.0.in_layers.0.bias", "input_blocks.15.0.in_layers.2.weight", "input_blocks.15.0.in_layers.2.bias", "input_blocks.15.0.emb_layers.1.weight", "input_blocks.15.0.emb_layers.1.bias", "input_blocks.15.0.out_layers.0.weight", "input_blocks.15.0.out_layers.0.bias", "input_blocks.15.0.out_layers.3.weight", "input_blocks.15.0.out_layers.3.bias", "input_blocks.18.0.in_layers.0.weight", "input_blocks.18.0.in_layers.0.bias", "input_blocks.18.0.in_layers.2.weight", "input_blocks.18.0.in_layers.2.bias", "input_blocks.18.0.emb_layers.1.weight", "input_blocks.18.0.emb_layers.1.bias", "input_blocks.18.0.out_layers.0.weight", "input_blocks.18.0.out_layers.0.bias", "input_blocks.18.0.out_layers.3.weight", "input_blocks.18.0.out_layers.3.bias", "output_blocks.2.4.in_layers.0.weight", "output_blocks.2.4.in_layers.0.bias", "output_blocks.2.4.in_layers.2.weight", "output_blocks.2.4.in_layers.2.bias", "output_blocks.2.4.emb_layers.1.weight", "output_blocks.2.4.emb_layers.1.bias", "output_blocks.2.4.out_layers.0.weight", "output_blocks.2.4.out_layers.0.bias", "output_blocks.2.4.out_layers.3.weight", "output_blocks.2.4.out_layers.3.bias", "output_blocks.5.4.in_layers.0.weight", "output_blocks.5.4.in_layers.0.bias", "output_blocks.5.4.in_layers.2.weight", "output_blocks.5.4.in_layers.2.bias", "output_blocks.5.4.emb_layers.1.weight", "output_blocks.5.4.emb_layers.1.bias", "output_blocks.5.4.out_layers.0.weight", "output_blocks.5.4.out_layers.0.bias", "output_blocks.5.4.out_layers.3.weight", "output_blocks.5.4.out_layers.3.bias", "output_blocks.6.3.norm.weight", "output_blocks.6.3.norm.bias", "output_blocks.6.3.qkv.weight", "output_blocks.6.3.qkv.bias", "output_blocks.6.3.proj_out.weight", "output_blocks.6.3.proj_out.bias", "output_blocks.7.3.norm.weight", "output_blocks.7.3.norm.bias", "output_blocks.7.3.qkv.weight", "output_blocks.7.3.qkv.bias", "output_blocks.7.3.proj_out.weight", "output_blocks.7.3.proj_out.bias", "output_blocks.8.4.in_layers.0.weight", "output_blocks.8.4.in_layers.0.bias", "output_blocks.8.4.in_layers.2.weight", "output_blocks.8.4.in_layers.2.bias", "output_blocks.8.4.emb_layers.1.weight", "output_blocks.8.4.emb_layers.1.bias", "output_blocks.8.4.out_layers.0.weight", "output_blocks.8.4.out_layers.0.bias", "output_blocks.8.4.out_layers.3.weight", "output_blocks.8.4.out_layers.3.bias", "output_blocks.8.3.norm.weight", "output_blocks.8.3.norm.bias", "output_blocks.8.3.qkv.weight", "output_blocks.8.3.qkv.bias", "output_blocks.8.3.proj_out.weight", "output_blocks.8.3.proj_out.bias", "output_blocks.11.3.in_layers.0.weight", "output_blocks.11.3.in_layers.0.bias", "output_blocks.11.3.in_layers.2.weight", "output_blocks.11.3.in_layers.2.bias", "output_blocks.11.3.emb_layers.1.weight", "output_blocks.11.3.emb_layers.1.bias", "output_blocks.11.3.out_layers.0.weight", "output_blocks.11.3.out_layers.0.bias", "output_blocks.11.3.out_layers.3.weight", "output_blocks.11.3.out_layers.3.bias", "output_blocks.14.1.in_layers.0.weight", "output_blocks.14.1.in_layers.0.bias", "output_blocks.14.1.in_layers.2.weight", "output_blocks.14.1.in_layers.2.bias", "output_blocks.14.1.emb_layers.1.weight", "output_blocks.14.1.emb_layers.1.bias", "output_blocks.14.1.out_layers.0.weight", "output_blocks.14.1.out_layers.0.bias", "output_blocks.14.1.out_layers.3.weight", "output_blocks.14.1.out_layers.3.bias", "output_blocks.17.1.in_layers.0.weight", "output_blocks.17.1.in_layers.0.bias", "output_blocks.17.1.in_layers.2.weight", "output_blocks.17.1.in_layers.2.bias", "output_blocks.17.1.emb_layers.1.weight", "output_blocks.17.1.emb_layers.1.bias", "output_blocks.17.1.out_layers.0.weight", "output_blocks.17.1.out_layers.0.bias", "output_blocks.17.1.out_layers.3.weight", "output_blocks.17.1.out_layers.3.bias".

**Comment by JiamingLiu-Jeremy** [comment]
Hi @ForMyCat,

We have successfully tested multiple times under different settings. Could you please share the settings of your main environments so that we could further debug it?
